
name: Package Main Branch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Zip the project for main
      run: |
        zip -r txjx.zip .
    - uses: actions/upload-artifact@v2
      with:
        name: txjx
        path: txjx.zip
